- name: Enabled Redis 7
  ansible.builtin.shell: dnf module disable redis -y; dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: Change Redis Conf File - IP Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Change Redis Conf File - Protected-mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Start Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes


