- name: Install Java
  ansible.builtin.include_role:
    name: common
    tasks_From: java

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: Load DB Schema
  ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/db/{ item }.sql
  loop:
    - schema
    - app-user
    - master-data

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup