- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Run MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup MySQL Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1