- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Run MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup MySQL Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:password token={{ token }} url=http://vault-int.mydevops.shop:8200') }}"