- name: Install & Start Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Run Payment Container
  community.docker.docker_container:
    name: payment
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
    state: started
    restart: true
    ports:
      - "8080:8080"
    env:
      MONGO: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:MONGO token={{ token }} url=http://vault-int.mydevops.shop:8200') }}"
      MONGO_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:MONGO_URL token={{ token }} url=http://vault-int.mydevops.shop:8200') }}"
      REDIS_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:REDIS_URL token={{ token }} url=http://vault-int.mydevops.shop:8200') }}"



  dnf install docker -y
  docker run -d -p 8080:8080 -e CART_HOST=cart-ip -e CART_PORT=8080 -e USER_HOST=user-ip -e USER_PORT=8080 -e AMQP_HOST=rabbitmq-ip 
  -e AMQP_USER=roboshop -e AMQP_PASS=roboshop123 public.ecr.aws/w8x4g9h7/roboshop-v3/payment

